---
- name: Add Jenkins apt repository key.
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "deb http://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: yes

- name: Ensure Jenkins is installed.
  apt: pkg=jenkins state=installed
