---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
